#!/usr/bin/env bash
# build.sh — assemble the self-contained root scripts from src/.
#
#   ./build.sh           regenerate ubuntu.sh docker.sh macos.sh macincloud.sh
#   ./build.sh --check    verify the committed scripts match src/ (CI drift gate)
#
# Each output = generated header + expanded body, where the body's
# `#@include NAME` lines are replaced by src/NAME and the `@DEFAULT_MODE@`
# token is replaced by that output's default mode.
set -eEuo pipefail

cd "$(dirname "$0")"
SRC=src

# output : body template : default mode
TARGETS=(
  "ubuntu.sh|ubuntu.body.sh|vm"
  "docker.sh|ubuntu.body.sh|container"
  "macos.sh|macos.body.sh|workstation"
  "macincloud.sh|macos.body.sh|noadmin"
)

expand() {
  # $1 = template path — emit it with #@include lines resolved (one level deep)
  local tpl="$1" line inc
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      '#@include '*)
        inc="${line#'#@include '}"
        [ -f "$SRC/$inc" ] || { echo "build: missing include $SRC/$inc" >&2; exit 1; }
        printf '# --- begin %s ---\n' "$inc"
        cat "$SRC/$inc"
        printf '# --- end %s ---\n' "$inc"
        ;;
      *) printf '%s\n' "$line" ;;
    esac
  done < "$tpl"
}

render() {
  # $1 = output name, $2 = template, $3 = mode
  local out="$1" tpl="$2" mode="$3"
  cat <<EOF
#!/usr/bin/env bash
# =====================================================================
#  $out — GENERATED by build.sh from $SRC/  — DO NOT EDIT THIS FILE
#  Edit $SRC/$tpl, $SRC/lib.sh or $SRC/versions.env, then run ./build.sh
#  Default mode: $mode
# =====================================================================
set -eEuo pipefail
EOF
  expand "$SRC/$tpl" | sed "s/@DEFAULT_MODE@/$mode/g"
}

check=0
[ "${1:-}" = "--check" ] && check=1
rc=0

for entry in "${TARGETS[@]}"; do
  IFS='|' read -r out tpl mode <<<"$entry"
  tmp="$(mktemp)"
  render "$out" "$tpl" "$mode" > "$tmp"
  if [ "$check" = 1 ]; then
    if diff -u "$out" "$tmp" >/dev/null 2>&1; then
      echo "ok    $out"
    else
      echo "DRIFT $out — run ./build.sh and commit" >&2
      diff -u "$out" "$tmp" >&2 || true
      rc=1
    fi
    rm -f "$tmp"
  else
    mv "$tmp" "$out"
    chmod +x "$out"
    echo "wrote $out (mode=$mode)"
  fi
done

exit "$rc"
