#!/usr/bin/env bash
# =====================================================================
#  macos.sh — GENERATED by build.sh from src/  — DO NOT EDIT THIS FILE
#  Edit src/macos.body.sh, src/lib.sh or src/versions.env, then run ./build.sh
#  Default mode: workstation
# =====================================================================
set -eEuo pipefail
# shellcheck shell=bash
# --- begin versions.env ---
# setupmyenv — pinned versions (single source of truth)
#
# Edit here, then run ./build.sh to regenerate the root scripts.
# CI fails if the committed scripts are out of sync with this file.
# Last re-baselined: 2026-09-03

# ---------------------------------------------------------------------------
# asdf-managed language / tool runtimes
# ---------------------------------------------------------------------------
NODEJS_VERSION=24.20.0
PYTHON_VERSION=3.13.15
GOLANG_VERSION=1.27.1
JAVA_VERSION=temurin-25.0.4+7
FLUTTER_VERSION=3.47.2-stable
TERRAFORM_VERSION=1.16.1
KUBECTL_VERSION=1.37.0
HELM_VERSION=4.2.4
SOPS_VERSION=3.13.3
RUBY_VERSION=3.4.10

# ---------------------------------------------------------------------------
# Bootstrap tooling
# ---------------------------------------------------------------------------
# asdf itself. On Linux it is installed from the GitHub release binary
# (Homebrew is no longer used on Linux); on macOS it comes from Homebrew.
ASDF_VERSION=0.20.0

# ---------------------------------------------------------------------------
# Android SDK
# ---------------------------------------------------------------------------
ANDROID_CMDLINE_TOOLS_BUILD=14742923
ANDROID_PLATFORM=android-36
ANDROID_BUILD_TOOLS=36.0.0

# ---------------------------------------------------------------------------
# OpenSSL 1.1 backward-compat shim (Ubuntu <= 22.04 only; see SPEC.md B10)
# ---------------------------------------------------------------------------
LIBSSL1_DEB=libssl1.1_1.1.1n-0+deb10u6_amd64.deb
LIBSSL1_DEB_BASEURL=http://security.debian.org/debian-security/pool/updates/main/o/openssl

# ---------------------------------------------------------------------------
# Optional SHA-256 checksums for directly-downloaded artifacts.
# Leave blank to skip verification (a warning is printed). Populate to enforce.
# These rotate on every version bump above — update them together.
# ---------------------------------------------------------------------------
ANDROID_CMDLINE_TOOLS_SHA256=
LIBSSL1_DEB_SHA256=
# --- end versions.env ---
# --- begin lib.sh ---
# shellcheck shell=bash
# setupmyenv — shared library (inlined into every generated script by build.sh)
# Targets bash 3.2+ (macOS system bash) and runs under `set -eEuo pipefail`.

# --------------------------------------------------------------------------
# Output helpers
# --------------------------------------------------------------------------
if [ -t 2 ]; then
  _c_reset=$'\033[0m'; _c_blue=$'\033[34m'; _c_yellow=$'\033[33m'
  _c_red=$'\033[31m';  _c_green=$'\033[32m'; _c_dim=$'\033[2m'
else
  _c_reset=; _c_blue=; _c_yellow=; _c_red=; _c_green=; _c_dim=
fi

log()  { printf '%s==>%s %s\n'   "$_c_blue"   "$_c_reset" "$*" >&2; }
ok()   { printf '%s ok %s %s\n'  "$_c_green"  "$_c_reset" "$*" >&2; }
warn() { printf '%swarn%s %s\n'  "$_c_yellow" "$_c_reset" "$*" >&2; }
err()  { printf '%serr %s %s\n'  "$_c_red"    "$_c_reset" "$*" >&2; }
die()  { err "$*"; exit 1; }
step() { printf '\n%s--- %s ---%s\n' "$_c_dim" "$*" "$_c_reset" >&2; }

# --------------------------------------------------------------------------
# Error trap — report the failing line and bail
# --------------------------------------------------------------------------
_on_err() {
  local ec=$? line=${1:-?}
  err "aborted at line ${line} (exit ${ec})"
  err "nothing was rolled back; fix the cause and re-run, or use --dry-run to preview"
  exit "$ec"
}

# --------------------------------------------------------------------------
# Dry-run plumbing
# --------------------------------------------------------------------------
DRY_RUN="${DRY_RUN:-0}"
is_dry_run() { [ "$DRY_RUN" = "1" ]; }

# run CMD...  — execute, or just print under --dry-run. Simple commands only
# (no pipes/redirections); guard those with `if is_dry_run; then ... fi`.
run() {
  if is_dry_run; then
    printf '   %s[dry-run]%s %s\n' "$_c_dim" "$_c_reset" "$*" >&2
    return 0
  fi
  "$@"
}

have()        { command -v "$1" >/dev/null 2>&1; }
require_cmd()  { have "$1" || die "required command not found: $1"; }

# --------------------------------------------------------------------------
# Platform detection
# --------------------------------------------------------------------------
os_id() {
  case "$(uname -s)" in
    Linux)  printf 'linux' ;;
    Darwin) printf 'macos' ;;
    *)      printf 'unknown' ;;
  esac
}

arch_tag() {
  case "$(uname -m)" in
    x86_64|amd64)  printf 'amd64' ;;
    aarch64|arm64) printf 'arm64' ;;
    i386|i686)     printf '386' ;;
    *)             printf 'unknown' ;;
  esac
}

# priv CMD...  — run CMD with sudo when $SUDO is non-empty, else run it directly.
# Honours --dry-run via run().
SUDO="${SUDO:-}"
priv() {
  if [ -n "$SUDO" ]; then run sudo "$@"; else run "$@"; fi
}

# --------------------------------------------------------------------------
# CLI arguments  (DEFAULT_MODE is substituted by build.sh per output file)
# --------------------------------------------------------------------------
MODE="${SETUPMYENV_MODE:-workstation}"
DO_ANDROID=1
DO_FLUTTER=1
TARGET_SHELL="${TARGET_SHELL:-}"

usage() {
  cat >&2 <<EOF
setupmyenv — provision a development toolchain

Usage: <script> [options]
   or: curl -fsSL <raw-url> | bash -s -- [options]

Options:
  --dry-run          Print every step without changing the system
  --no-android       Skip the Android SDK / command-line tools
  --no-flutter       Skip Flutter
  --container        Container mode: run as root, no sudo, no Homebrew
  --no-admin         macOS without admin rights (Homebrew into \$HOME/.brew)
  --shell <name>     Which rc file to configure: bash | zsh  (default: auto)
  -h, --help         This help

Environment:
  DRY_RUN=1          Same as --dry-run
  ENV=zsh|bash       Legacy alias for --shell
  SETUPMYENV_MODE=…  vm | container | workstation | noadmin
  SKIP_CHECKSUM=1    Do not verify download checksums (not recommended)
EOF
}

parse_args() {
  # legacy: ENV=zsh|bash selects the target shell
  if [ -z "$TARGET_SHELL" ] && [ -n "${ENV:-}" ]; then TARGET_SHELL="$ENV"; fi

  while [ $# -gt 0 ]; do
    case "$1" in
      --dry-run)     DRY_RUN=1 ;;
      --no-android)  DO_ANDROID=0 ;;
      --no-flutter)  DO_FLUTTER=0 ;;
      --container)   MODE=container ;;
      --no-admin)    MODE=noadmin ;;
      --shell)       shift; TARGET_SHELL="${1:-}" ;;
      --shell=*)     TARGET_SHELL="${1#*=}" ;;
      -h|--help)     usage; exit 0 ;;
      *)             err "unknown option: $1"; usage; exit 2 ;;
    esac
    shift
  done

  case "$MODE" in
    vm|container|workstation|noadmin) ;;
    *) die "invalid mode: $MODE" ;;
  esac
}

# --------------------------------------------------------------------------
# Shell / profile resolution
# --------------------------------------------------------------------------
PROFILE_FILES=()

resolve_shell_and_profiles() {
  if [ -z "$TARGET_SHELL" ]; then
    case "${SHELL:-}" in
      */zsh)  TARGET_SHELL=zsh ;;
      */bash) TARGET_SHELL=bash ;;
      *)      if [ "$(os_id)" = macos ]; then TARGET_SHELL=zsh; else TARGET_SHELL=bash; fi ;;
    esac
  fi
  case "$TARGET_SHELL" in
    zsh)  PROFILE_FILES=("$HOME/.zshrc") ;;
    bash)
      if [ "$(os_id)" = macos ]; then PROFILE_FILES=("$HOME/.bash_profile")
      else PROFILE_FILES=("$HOME/.profile"); fi
      ;;
    *) die "unsupported --shell: $TARGET_SHELL (want bash or zsh)" ;;
  esac
  # noadmin (MacinCloud + GitLab runner) also feeds a bash login shell
  if [ "$MODE" = noadmin ]; then PROFILE_FILES=("${PROFILE_FILES[@]}" "$HOME/.bashrc"); fi
  for _pf in "${PROFILE_FILES[@]}"; do [ -e "$_pf" ] || { is_dry_run || : > "$_pf"; }; done
  log "shell: $TARGET_SHELL   profile(s): ${PROFILE_FILES[*]}"
}

# profile_append_once MARKER  (content on stdin)
# Writes a fenced block once per profile file; re-runs are no-ops.
profile_append_once() {
  local marker="$1" content begin end f
  begin="# >>> setupmyenv:${marker} >>>"
  end="# <<< setupmyenv:${marker} <<<"
  content="$(cat)"
  for f in "${PROFILE_FILES[@]}"; do
    if [ -f "$f" ] && grep -qF "$begin" "$f" 2>/dev/null; then
      log "profile block '${marker}' already in ${f##*/} — skipping"
      continue
    fi
    if is_dry_run; then
      printf '   %s[dry-run]%s append block %s to %s\n' "$_c_dim" "$_c_reset" "$marker" "$f" >&2
      continue
    fi
    { printf '\n%s\n%s\n%s\n' "$begin" "$content" "$end"; } >> "$f"
    ok "wrote block '${marker}' to ${f##*/}"
  done
}

# rcfile_line_once FILE LINE  — append LINE to FILE unless already present
rcfile_line_once() {
  local file="$1" line="$2"
  if [ -f "$file" ] && grep -qF -- "$line" "$file" 2>/dev/null; then return 0; fi
  if is_dry_run; then
    printf '   %s[dry-run]%s add %q to %s\n' "$_c_dim" "$_c_reset" "$line" "$file" >&2
    return 0
  fi
  printf '%s\n' "$line" >> "$file"
}

# --------------------------------------------------------------------------
# Downloads + integrity
# --------------------------------------------------------------------------
# verify_sha256 FILE EXPECTED
verify_sha256() {
  local file="$1" expected="$2" actual=""
  if [ "${SKIP_CHECKSUM:-0}" = "1" ]; then warn "SKIP_CHECKSUM=1 — not verifying ${file##*/}"; return 0; fi
  if [ -z "$expected" ]; then
    warn "no checksum pinned for ${file##*/} — skipping verification (set it in versions.env)"
    return 0
  fi
  if have sha256sum; then actual="$(sha256sum "$file" | awk '{print $1}')"
  elif have shasum; then actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  else warn "no sha256 tool available — cannot verify ${file##*/}"; return 0
  fi
  if [ "$actual" != "$expected" ]; then
    die "checksum mismatch for ${file##*/}: expected $expected, got $actual"
  fi
  ok "checksum verified: ${file##*/}"
}

# download URL DEST [SHA256]
download() {
  local url="$1" dest="$2" sha="${3:-}"
  if is_dry_run; then
    printf '   %s[dry-run]%s download %s -> %s\n' "$_c_dim" "$_c_reset" "$url" "$dest" >&2
    return 0
  fi
  log "downloading ${url##*/}"
  curl -fsSL --retry 3 --retry-delay 2 -o "$dest" "$url"
  verify_sha256 "$dest" "$sha"
}

# --------------------------------------------------------------------------
# asdf
# --------------------------------------------------------------------------
# Put asdf + its shims on PATH for the remainder of THIS process (no sourcing
# of the user rc file — that broke the zsh flow, see SPEC.md B2/B3).
ensure_asdf_env() {
  export ASDF_DATA_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}"
  mkdir -p "$ASDF_DATA_DIR"
  case ":$PATH:" in
    *":$ASDF_DATA_DIR/shims:"*) ;;
    *) export PATH="$ASDF_DATA_DIR/shims:$PATH" ;;
  esac
}

# asdf_install_tool PLUGIN VERSION
asdf_install_tool() {
  local plugin="$1" version="$2"
  if is_dry_run; then
    printf '   %s[dry-run]%s asdf %s %s\n' "$_c_dim" "$_c_reset" "$plugin" "$version" >&2
    return 0
  fi
  step "asdf: $plugin $version"
  asdf plugin add "$plugin" 2>/dev/null || true
  asdf install "$plugin" "$version"
  asdf set -u "$plugin" "$version"
}

# Arm the error trap now that _on_err is defined.
trap '_on_err $LINENO' ERR
# --- end lib.sh ---

# ==========================================================================
# macOS body  (modes: workstation, noadmin)
#   workstation : official Homebrew, admin user
#   noadmin     : Homebrew cloned into $HOME/.brew (e.g. MacinCloud), also
#                 mirrors config into ~/.bashrc for a GitLab runner
# ==========================================================================

BREW=""   # resolved path to the brew binary

preflight() {
  [ "$(os_id)" = macos ] || die "macos.sh targets macOS — on Linux run ubuntu.sh"
  if ! xcode-select -p >/dev/null 2>&1; then
    warn "Xcode Command Line Tools not detected."
    warn "Run:  xcode-select --install && sudo xcodebuild -license accept"
    is_dry_run || die "install the Command Line Tools first"
  fi
}

install_homebrew() {
  if have brew; then BREW="$(command -v brew)"; log "brew present: $BREW"; return 0; fi

  if [ "$MODE" = noadmin ]; then
    step "Homebrew into \$HOME/.brew (no admin)"
    if ! is_dry_run; then
      [ -d "$HOME/.brew" ] || git clone --depth=1 https://github.com/Homebrew/brew "$HOME/.brew"
    fi
    BREW="$HOME/.brew/bin/brew"
    profile_append_once homebrew <<'EOF'
# homebrew
export PATH="$HOME/.brew/bin:$HOME/.brew/sbin:$PATH"
EOF
  else
    step "Homebrew (official installer)"
    if is_dry_run; then
      log "[dry-run] run Homebrew install.sh"
    else
      NONINTERACTIVE=1 /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    if [ -x /opt/homebrew/bin/brew ]; then BREW=/opt/homebrew/bin/brew
    elif [ -x /usr/local/bin/brew ]; then BREW=/usr/local/bin/brew
    else BREW="brew"; fi
    profile_append_once homebrew <<EOF
# homebrew
eval "\$($BREW shellenv)"
EOF
  fi

  if ! is_dry_run && [ -x "$BREW" ]; then eval "$("$BREW" shellenv)"; fi
}

brew_install() {
  if is_dry_run; then log "[dry-run] brew install $*"; return 0; fi
  "$BREW" install "$@"
}

install_brew_tools() {
  step "brew: asdf + build deps"
  # asdf from Homebrew is fine (0.16+ Go binary); we DO NOT source asdf.sh
  local pkgs="asdf jq openssl@3 readline sqlite3 xz zlib tcl-tk libyaml"
  if [ "$MODE" != noadmin ]; then pkgs="$pkgs awscli fastlane cocoapods"; fi
  # shellcheck disable=SC2086
  brew_install $pkgs
}

profile_core() {
  profile_append_once core <<'EOF'
# locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
# gpg: route the pinentry prompt to the tty for signed git commits
export GPG_TTY=$(tty)
EOF
}

install_asdf_env() {
  ensure_asdf_env
}

install_runtimes() {
  ensure_asdf_env
  asdf_install_tool nodejs    "$NODEJS_VERSION"
  asdf_install_tool python    "$PYTHON_VERSION"
  asdf_install_tool golang    "$GOLANG_VERSION"
  asdf_install_tool java      "$JAVA_VERSION"
  if [ "$DO_FLUTTER" = 1 ]; then
    asdf_install_tool flutter "$FLUTTER_VERSION"
  else
    log "skipping flutter (--no-flutter)"
  fi
  asdf_install_tool terraform "$TERRAFORM_VERSION"
  asdf_install_tool kubectl   "$KUBECTL_VERSION"
  asdf_install_tool helm      "$HELM_VERSION"
  asdf_install_tool sops      "$SOPS_VERSION"
  asdf_install_tool ruby      "$RUBY_VERSION"
  is_dry_run || asdf reshim
}

configure_asdf() {
  rcfile_line_once "$HOME/.asdfrc" "legacy_version_file = yes"
  rcfile_line_once "$HOME/.asdfrc" "java_macos_integration_enable = yes"

  profile_append_once asdf <<'EOF'
# asdf
export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"
[ -f "$ASDF_DATA_DIR/plugins/java/set-java-home.zsh" ] && . "$ASDF_DATA_DIR/plugins/java/set-java-home.zsh"
EOF

  is_dry_run && return 0
  have asdf || return 0
  mkdir -p "$HOME/.asdf/completions"
  asdf completion zsh > "$HOME/.asdf/completions/_asdf" 2>/dev/null || true
  profile_append_once asdf-completion <<'EOF'
# asdf completions
fpath=("$HOME/.asdf/completions" $fpath)
autoload -Uz compinit && compinit
EOF
}

activate_java() {
  is_dry_run && return 0
  if asdf where java >/dev/null 2>&1; then
    JAVA_HOME="$(asdf where java)"; export JAVA_HOME
    log "JAVA_HOME=$JAVA_HOME"
  fi
}

install_extra_tools() {
  [ "$MODE" != noadmin ] && return 0   # workstation got these from brew
  ensure_asdf_env
  step "fastlane + cocoapods (RubyGems, no-admin)"
  if is_dry_run; then
    log "[dry-run] gem install fastlane cocoapods"
  elif have gem; then
    gem install --no-document fastlane cocoapods
  fi
  have aws || warn "aws cli not installed (needs admin); install manually if required"
}

install_android() {
  if [ "$DO_ANDROID" != 1 ]; then log "skipping Android SDK (--no-android)"; return 0; fi
  step "Android command-line tools"
  local home="$HOME/Library/Android/sdk" url
  url="https://dl.google.com/android/repository/commandlinetools-mac-${ANDROID_CMDLINE_TOOLS_BUILD}_latest.zip"

  if [ -x "$home/cmdline-tools/latest/bin/sdkmanager" ]; then
    log "cmdline-tools already installed at $home"
  else
    download "$url" /tmp/android-cmdline-tools.zip "$ANDROID_CMDLINE_TOOLS_SHA256"
    if ! is_dry_run; then
      mkdir -p "$home/cmdline-tools"
      rm -rf "$home/cmdline-tools/latest" "$home/cmdline-tools/cmdline-tools"
      unzip -q /tmp/android-cmdline-tools.zip -d "$home/cmdline-tools"
      mv "$home/cmdline-tools/cmdline-tools" "$home/cmdline-tools/latest"
      rm -f /tmp/android-cmdline-tools.zip
    fi
  fi

  profile_append_once android <<'EOF'
# android
export ANDROID_HOME="$HOME/Library/Android/sdk"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator"
EOF

  export ANDROID_HOME="$home" ANDROID_SDK_ROOT="$home"
  export PATH="$PATH:$home/cmdline-tools/latest/bin"
  if is_dry_run; then
    log "[dry-run] accept licenses; sdkmanager platform-tools platforms;${ANDROID_PLATFORM} build-tools;${ANDROID_BUILD_TOOLS}"
    return 0
  fi
  yes | sdkmanager --licenses >/dev/null 2>&1 || true
  sdkmanager --install "platform-tools" "platforms;${ANDROID_PLATFORM}" "build-tools;${ANDROID_BUILD_TOOLS}"
}

main() {
  parse_args "$@"
  is_dry_run && warn "DRY RUN — no changes will be made"
  log "setupmyenv: mode=$MODE  os=$(os_id)/$(arch_tag)"

  # macOS scripts always configure zsh unless told otherwise
  [ -z "$TARGET_SHELL" ] && TARGET_SHELL=zsh
  resolve_shell_and_profiles

  preflight
  profile_core
  install_homebrew
  install_brew_tools
  install_asdf_env
  install_runtimes
  configure_asdf
  activate_java
  install_extra_tools
  install_android

  step "done"
  ok "toolchain ready — restart your shell:  exec \"\$SHELL\" -l"
}

main "$@"
